"""empty message

Revision ID: 0460fb975e00
Revises: 
Create Date: 2020-06-11 13:40:07.597825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0460fb975e00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_esgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('esg_risk_category', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockquotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('companyName', sa.String(length=250), nullable=True),
    sa.Column('primaryExchange', sa.String(length=60), nullable=True),
    sa.Column('peRatio', sa.Numeric(), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('openPrice', sa.Numeric(), nullable=True),
    sa.Column('closePrice', sa.Numeric(), nullable=True),
    sa.Column('marketOpen', sa.Numeric(), nullable=True),
    sa.Column('latestPrice', sa.Numeric(), nullable=True),
    sa.Column('latestVolume', sa.Numeric(), nullable=True),
    sa.Column('previousClose', sa.Numeric(), nullable=True),
    sa.Column('change', sa.Numeric(), nullable=True),
    sa.Column('changePercent', sa.Float(), nullable=True),
    sa.Column('marketCap', sa.Numeric(), nullable=True),
    sa.Column('avgTotalVolume', sa.Numeric(), nullable=True),
    sa.Column('week52High', sa.Numeric(), nullable=True),
    sa.Column('week52Low', sa.Numeric(), nullable=True),
    sa.Column('ytdChange', sa.Numeric(), nullable=True),
    sa.Column('previousVolume', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('p_type', sa.String(length=200), nullable=True),
    sa.Column('include_nyse', sa.Boolean(), nullable=True),
    sa.Column('include_nasdaq', sa.Boolean(), nullable=True),
    sa.Column('include_nyse_arca', sa.Boolean(), nullable=True),
    sa.Column('include_nyse_american', sa.Boolean(), nullable=True),
    sa.Column('exclude_communications', sa.Boolean(), nullable=True),
    sa.Column('exclude_energy_minerals', sa.Boolean(), nullable=True),
    sa.Column('exclude_health_technology', sa.Boolean(), nullable=True),
    sa.Column('exclude_non_energy_minerals', sa.Boolean(), nullable=True),
    sa.Column('exclude_utilities', sa.Boolean(), nullable=True),
    sa.Column('exclude_technology_services', sa.Boolean(), nullable=True),
    sa.Column('exclude_consumer_durables', sa.Boolean(), nullable=True),
    sa.Column('exclude_distribution_services', sa.Boolean(), nullable=True),
    sa.Column('exclude_finance', sa.Boolean(), nullable=True),
    sa.Column('exclude_process_industries', sa.Boolean(), nullable=True),
    sa.Column('exclude_producer_manufacturing', sa.Boolean(), nullable=True),
    sa.Column('exclude_commercial_services', sa.Boolean(), nullable=True),
    sa.Column('exclude_industrial_services', sa.Boolean(), nullable=True),
    sa.Column('exclude_transportation', sa.Boolean(), nullable=True),
    sa.Column('exclude_consumer_non_durables', sa.Boolean(), nullable=True),
    sa.Column('exclude_health_services', sa.Boolean(), nullable=True),
    sa.Column('exclude_retail_trade', sa.Boolean(), nullable=True),
    sa.Column('exclude_electronic_technology', sa.Boolean(), nullable=True),
    sa.Column('esg_risk_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('stockquotes')
    op.drop_table('stock_esgs')
    # ### end Alembic commands ###
