"""empty message

Revision ID: 3ae806a7dfd8
Revises: cf599a78d899
Create Date: 2020-05-20 19:35:41.524519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae806a7dfd8'
down_revision = 'cf599a78d899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('security', sa.String(length=500), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('sub_industry', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_sector')
    # ### end Alembic commands ###
