"""empty message

Revision ID: 4e3fe8bf09f6
Revises: 
Create Date: 2020-06-05 15:59:44.851822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3fe8bf09f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_esgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=True),
    sa.Column('esg_risk_category', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('portfolio', sa.Column('esg_risk_category', sa.Integer(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_commercial_services', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_communications', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_consumer_durables', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_consumer_non_durables', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_distribution_services', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_electronic_technology', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_energy_minerals', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_finance', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_health_services', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_health_technology', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_industrial_services', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_non_energy_minerals', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_process_industries', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_producer_manufacturing', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_retail_trade', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_technology_services', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_transportation', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('exclude_utilities', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('include_nasdaq', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('include_nyse', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('include_nyse_american', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('include_nyse_arca', sa.Boolean(), nullable=True))
    op.drop_column('portfolio', 're')
    op.drop_column('portfolio', 'target')
    op.drop_column('portfolio', 'health_care')
    op.drop_column('portfolio', 'financial')
    op.drop_column('portfolio', 'priority')
    op.drop_column('portfolio', 'us_equities')
    op.drop_column('portfolio', 'initial')
    op.drop_column('portfolio', 'materials')
    op.drop_column('portfolio', 'real_estate')
    op.drop_column('portfolio', 'treasury')
    op.drop_column('portfolio', 'restricted')
    op.drop_column('portfolio', 'con_staples')
    op.drop_column('portfolio', 'con_dis')
    op.drop_column('portfolio', 'utilitie')
    op.drop_column('portfolio', 'industrials')
    op.drop_column('portfolio', 'commodities')
    op.drop_column('portfolio', 'mlps')
    op.drop_column('portfolio', 'int_equities')
    op.drop_column('portfolio', 'tolerance')
    op.drop_column('portfolio', 'us_bonds')
    op.drop_column('portfolio', 'strategy')
    op.drop_column('portfolio', 'tech')
    op.drop_column('portfolio', 'energy')
    op.drop_column('portfolio', 'telco')
    op.drop_column('portfolio', 'int_bonds')
    op.drop_column('portfolio', 'etf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('etf', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('int_bonds', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('telco', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('energy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('tech', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('us_bonds', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('tolerance', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('int_equities', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('mlps', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('commodities', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('industrials', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('utilitie', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('con_dis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('con_staples', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('restricted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('treasury', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('real_estate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('materials', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('initial', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('us_equities', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('priority', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('financial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('health_care', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('target', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('re', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('portfolio', 'include_nyse_arca')
    op.drop_column('portfolio', 'include_nyse_american')
    op.drop_column('portfolio', 'include_nyse')
    op.drop_column('portfolio', 'include_nasdaq')
    op.drop_column('portfolio', 'exclude_utilities')
    op.drop_column('portfolio', 'exclude_transportation')
    op.drop_column('portfolio', 'exclude_technology_services')
    op.drop_column('portfolio', 'exclude_retail_trade')
    op.drop_column('portfolio', 'exclude_producer_manufacturing')
    op.drop_column('portfolio', 'exclude_process_industries')
    op.drop_column('portfolio', 'exclude_non_energy_minerals')
    op.drop_column('portfolio', 'exclude_industrial_services')
    op.drop_column('portfolio', 'exclude_health_technology')
    op.drop_column('portfolio', 'exclude_health_services')
    op.drop_column('portfolio', 'exclude_finance')
    op.drop_column('portfolio', 'exclude_energy_minerals')
    op.drop_column('portfolio', 'exclude_electronic_technology')
    op.drop_column('portfolio', 'exclude_distribution_services')
    op.drop_column('portfolio', 'exclude_consumer_non_durables')
    op.drop_column('portfolio', 'exclude_consumer_durables')
    op.drop_column('portfolio', 'exclude_communications')
    op.drop_column('portfolio', 'exclude_commercial_services')
    op.drop_column('portfolio', 'esg_risk_category')
    op.drop_table('stock_esgs')
    # ### end Alembic commands ###
