"""empty message

Revision ID: 8c9504ff885b
Revises: beb72f91b20e
Create Date: 2020-05-18 11:23:19.235857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c9504ff885b'
down_revision = 'beb72f91b20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('holding_long', sa.String(length=250), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('restriction')
    op.drop_table('strategy')
    op.drop_table('structure')
    op.drop_table('risk')
    op.add_column('portfolio', sa.Column('commodities', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('con_dis', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('con_staples', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('energy', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('etf', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('financial', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('health_care', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('industrials', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('initial', sa.Numeric(), nullable=True))
    op.add_column('portfolio', sa.Column('int_bonds', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('int_equities', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('materials', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('mlps', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('portfolio', sa.Column('priority', sa.String(length=100), nullable=True))
    op.add_column('portfolio', sa.Column('re', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('real_estate', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('restricted', sa.String(length=500), nullable=True))
    op.add_column('portfolio', sa.Column('strategy', sa.String(length=50), nullable=True))
    op.add_column('portfolio', sa.Column('target', sa.Numeric(), nullable=True))
    op.add_column('portfolio', sa.Column('tech', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('telco', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('tolerance', sa.Numeric(), nullable=True))
    op.add_column('portfolio', sa.Column('treasury', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('us_bonds', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('us_equities', sa.Boolean(), nullable=True))
    op.add_column('portfolio', sa.Column('utilitie', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'portfolio', 'user', ['owner_id'], ['id'])
    op.drop_column('portfolio', 'price')
    op.drop_column('portfolio', 'holding')
    op.drop_column('portfolio', 'shares')
    op.drop_column('portfolio', 'change')
    op.drop_column('portfolio', 'holding_long')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('holding_long', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('change', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('shares', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('holding', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('portfolio', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'utilitie')
    op.drop_column('portfolio', 'us_equities')
    op.drop_column('portfolio', 'us_bonds')
    op.drop_column('portfolio', 'treasury')
    op.drop_column('portfolio', 'tolerance')
    op.drop_column('portfolio', 'telco')
    op.drop_column('portfolio', 'tech')
    op.drop_column('portfolio', 'target')
    op.drop_column('portfolio', 'strategy')
    op.drop_column('portfolio', 'restricted')
    op.drop_column('portfolio', 'real_estate')
    op.drop_column('portfolio', 're')
    op.drop_column('portfolio', 'priority')
    op.drop_column('portfolio', 'owner_id')
    op.drop_column('portfolio', 'mlps')
    op.drop_column('portfolio', 'materials')
    op.drop_column('portfolio', 'int_equities')
    op.drop_column('portfolio', 'int_bonds')
    op.drop_column('portfolio', 'initial')
    op.drop_column('portfolio', 'industrials')
    op.drop_column('portfolio', 'health_care')
    op.drop_column('portfolio', 'financial')
    op.drop_column('portfolio', 'etf')
    op.drop_column('portfolio', 'energy')
    op.drop_column('portfolio', 'con_staples')
    op.drop_column('portfolio', 'con_dis')
    op.drop_column('portfolio', 'commodities')
    op.create_table('risk',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('initial', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('target', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('tolerance', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='risk_pkey')
    )
    op.create_table('structure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('us_equities', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('us_bonds', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('treasury', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('int_equities', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('commodities', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('real_estate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('mlps', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('int_bonds', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='structure_pkey')
    )
    op.create_table('strategy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='strategy_pkey')
    )
    op.create_table('restriction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('financial', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('utilitie', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('health_care', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('con_dis', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('energy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('industrials', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('con_staples', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('re', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tech', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('materials', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('telco', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('etf', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('restricted', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='restriction_pkey')
    )
    op.drop_table('position')
    # ### end Alembic commands ###
