"""empty message

Revision ID: beb72f91b20e
Revises: c9741edd17da
Create Date: 2020-05-17 20:49:10.807251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb72f91b20e'
down_revision = 'c9741edd17da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('strategy', sa.String(length=50), nullable=True))
    op.drop_column('strategy', 'growth')
    op.drop_column('strategy', 'none')
    op.drop_column('strategy', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('value', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('none', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('strategy', sa.Column('growth', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('strategy', 'strategy')
    # ### end Alembic commands ###
