"""empty message

Revision ID: cf599a78d899
Revises: 69aed37271bd
Create Date: 2020-05-19 16:13:01.173408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf599a78d899'
down_revision = '69aed37271bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'time')
    op.drop_column('stocks', 'open')
    op.drop_column('stocks', 'lastest_price')
    op.drop_column('stocks', 'company_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('company_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('stocks', sa.Column('lastest_price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('stocks', sa.Column('open', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('stocks', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
